title: Silo.ist
short_title: the words of Silo
email: stefano.cecere@gmail.com
description: the complete words and works archive by Mario Rodriguez Cobos
baseurl: ""
url: "http://silo.ist" 
# twitter_username: jekyllrb
github_username:  siloist
github_repo:  silo.ist

permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-sitemap
  - jekyll-feed

# Reading Files
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README
encoding: "utf-8"
markdown_ext: "md"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      section: texts

related_projects:
  -
      name: Silo.net
      link: http://silo.net
  