title: Silo.ist
short_title: the words of Silo
email: stefano.cecere@gmail.com
description: the complete words and works archive by Mario Rodriguez Cobos
baseurl: "/silo"
url: "https://siloist.github.io/silo"
github_username: siloist
github_repo: archive

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
sass:
  # sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-sitemap
  - jekyll-feed

# Reading Files
include:
  - _pages
exclude:
  - README
  - Rakefile
encoding: "utf-8"
markdown_ext: "md"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      section: texts

related_projects:
  -
      name: Silo.net
      link: http://silo.net
